# Generated by Django 5.2 on 2025-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlist_image_alter_wishlistitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_images/'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_items_images/'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
