# Generated by Django 5.2 on 2025-04-28 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_alter_wishlist_image_alter_wishlistitem_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
